### * https://www.inflearn.com/course-status-2/ (Section 4)

In [1]:
import tensorflow as tf

## * multi-variable linear regression

In [2]:
## Load data
x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data =[152, 185, 180, 196, 142]

## Placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

## random_normal is ([1]) because each weight is one(a) value
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b

## cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

## Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

## Launch the graph in a session
sess = tf.Session()
## Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict={x1:x1_data,
                                               x2:x2_data,
                                               x3:x3_data,
                                               Y:y_data})
    if step % 20 == 0:
        print(' step: ', step, '\n', "Cost: ", cost_val, "\n Prediction:\n", hy_val, '\n\n')

 step:  0 
 Cost:  100690.47 
 Prediction:
 [-123.39799 -158.42076 -151.00749 -164.00089 -123.52564] 


 step:  20 
 Cost:  26.40686 
 Prediction:
 [158.0793  179.96782 182.37419 199.04695 134.59508] 


 step:  40 
 Cost:  26.130625 
 Prediction:
 [158.043   179.99767 182.36542 199.04091 134.63321] 


 step:  60 
 Cost:  25.857342 
 Prediction:
 [158.00432 180.02426 182.35368 199.03162 134.66881] 


 step:  80 
 Cost:  25.587011 
 Prediction:
 [157.96585 180.05072 182.34201 199.02237 134.70421] 


 step:  100 
 Cost:  25.319561 
 Prediction:
 [157.9276  180.07704 182.3304  199.01317 134.73943] 


 step:  120 
 Cost:  25.055088 
 Prediction:
 [157.88954 180.10318 182.31883 199.00397 134.77441] 


 step:  140 
 Cost:  24.79341 
 Prediction:
 [157.85172 180.12921 182.30734 198.99486 134.80925] 


 step:  160 
 Cost:  24.534573 
 Prediction:
 [157.81407 180.15508 182.29591 198.9858  134.84389] 


 step:  180 
 Cost:  24.278389 
 Prediction:
 [157.77664 180.18083 182.28455 198.97675 134.878

 step:  1700 
 Cost:  11.075752 
 Prediction:
 [155.45602 181.77779 181.58119 198.40799 137.02472] 


 step:  1720 
 Cost:  10.964265 
 Prediction:
 [155.43146 181.79471 181.57379 198.40186 137.04755] 


 step:  1740 
 Cost:  10.853982 
 Prediction:
 [155.40707 181.81152 181.5664  198.39575 137.07028] 


 step:  1760 
 Cost:  10.744852 
 Prediction:
 [155.38277 181.82823 181.55905 198.38965 137.09286] 


 step:  1780 
 Cost:  10.636912 
 Prediction:
 [155.35863 181.84486 181.55174 198.38359 137.11534] 


 step:  1800 
 Cost:  10.530142 
 Prediction:
 [155.33461 181.8614  181.54448 198.37758 137.1377 ] 


 step:  1820 
 Cost:  10.424518 
 Prediction:
 [155.31073 181.87785 181.53728 198.37157 137.15993] 


 step:  1840 
 Cost:  10.320009 
 Prediction:
 [155.28697 181.89421 181.53009 198.36562 137.18205] 


 step:  1860 
 Cost:  10.216628 
 Prediction:
 [155.26335 181.91048 181.52296 198.35966 137.20406] 


 step:  1880 
 Cost:  10.114317 
 Prediction:
 [155.23985 181.92668 181.51587 198.

In [3]:
## Load data
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

## Placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

## Hypothesis
hypothesis = tf.matmul(X, W) + b
## Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
## Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

## Launch the graph in a session
sess = tf.Session()
## Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict={X:x_data, Y:y_data})
    if step % 20 == 0:
        print(' step: ', step, '\n',
              'Cost: ', cost,
              '\n Prediction:\n', hy_val, '\n\n')

 step:  0 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[-4.581658 ]
 [14.906035 ]
 [ 3.880851 ]
 [ 6.9830623]
 [14.302588 ]] 


 step:  20 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[141.97037]
 [190.96158]
 [177.3978 ]
 [195.93228]
 [148.57178]] 


 step:  40 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[142.01869]
 [190.9311 ]
 [177.41393]
 [195.9435 ]
 [148.53175]] 


 step:  60 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[142.06541]
 [190.89917]
 [177.42834]
 [195.95291]
 [148.49072]] 


 step:  80 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[142.1119 ]
 [190.86742]
 [177.44273]
 [195.96227]
 [148.44994]] 


 step:  100 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[142.15813]
 [190.83582]
 [177.45703]
 [195.97156]
 [148.40936]] 


 step:  120 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[142.20412]
 [190.80443]
 [177.47128]
 [195.98083]
 [148.36902]] 


 step:  140 
 Cost:  Tensor(

 step:  1180 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[144.31969]
 [189.3596 ]
 [178.12648]
 [196.40047]
 [146.51886]] 


 step:  1200 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[144.3541 ]
 [189.3361 ]
 [178.13715]
 [196.40717]
 [146.48888]] 


 step:  1220 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[144.38834]
 [189.31271]
 [178.14777]
 [196.41385]
 [146.45908]] 


 step:  1240 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[144.42241]
 [189.2895 ]
 [178.15836]
 [196.42047]
 [146.42943]] 


 step:  1260 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[144.45628]
 [189.26636]
 [178.16885]
 [196.42706]
 [146.39993]] 


 step:  1280 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[144.48997]
 [189.24336]
 [178.1793 ]
 [196.43361]
 [146.3706 ]] 


 step:  1300 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[144.5235 ]
 [189.22049]
 [178.18971]
 [196.44012]
 [146.34145]] 


 step:  1320 
 Cost:

### * Retrieve data from a file as Tensorflow

In [4]:
import numpy as np

In [5]:
xy = np.loadtxt('./INFLEARN_Deep_Learning_Zero_To_All/data-01-test-score.csv',
                delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [6]:
## Make sure the shape and data are OK
print(xy.shape, '\n')
print(x_data.shape, '\n', x_data, '\n', len(x_data), '\n')
print(y_data.shape, '\n', y_data, '\n', len(y_data))

(25, 4) 

(25, 3) 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
 25 

(25, 1) 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
 25


In [16]:
tf.set_random_seed(777)  # for reproducibility

## Placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

## Hypothesis
hypothesis = tf.matmul(X, W) + b

## Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

## Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

## Launch the graph in a session
sess = tf.Session()
## Initailizes global variables in the graph
sess.run(tf.global_variables_initializer())

## Set up feed_dict variables inside the loop
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict={X:x_data, Y:y_data})
    if step % 10 == 0:
        print(' step: ', step, '\n',
              'Cost: ', cost_val,
              '\n Prediction:\n', hy_val, '\n\n')

## Ask my score
print("Your score will be ", sess.run(hypothesis,
                                      feed_dict={X:[[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X:[[60, 70, 100], 
                                                      [90, 100, 80]]}))

 step:  0 
 Cost:  109824.8 
 Prediction:
 [[-152.201  ]
 [-195.72394]
 [-186.52248]
 [-201.65503]
 [-153.35759]
 [-111.64235]
 [-144.66345]
 [ -98.23015]
 [-183.74532]
 [-167.63007]
 [-144.70578]
 [-147.55533]
 [-194.64142]
 [-164.72302]
 [-147.02249]
 [-195.93745]
 [-162.65157]
 [-169.9864 ]
 [-183.82729]
 [-162.67896]
 [-172.26514]
 [-181.14102]
 [-163.57535]
 [-157.75797]
 [-201.70793]] 


 step:  10 
 Cost:  41.52921 
 Prediction:
 [[157.17032 ]
 [176.15268 ]
 [179.87245 ]
 [197.37787 ]
 [130.26822 ]
 [ 97.46971 ]
 [154.0167  ]
 [123.178024]
 [163.81053 ]
 [154.2971  ]
 [143.06822 ]
 [136.2143  ]
 [183.89493 ]
 [149.95285 ]
 [153.03677 ]
 [181.427   ]
 [137.04729 ]
 [188.45012 ]
 [177.04652 ]
 [160.21284 ]
 [177.99023 ]
 [167.72746 ]
 [170.36179 ]
 [154.16122 ]
 [183.69229 ]] 


 step:  20 
 Cost:  36.118835 
 Prediction:
 [[159.28775]
 [178.73782]
 [182.39886]
 [200.13065]
 [132.2487 ]
 [ 98.93659]
 [156.06795]
 [124.68452]
 [166.23752]
 [156.55162]
 [145.05508]
 [138.19165]
 [18

 [186.58122]] 


 step:  240 
 Cost:  32.626183 
 Prediction:
 [[158.87756 ]
 [179.09622 ]
 [182.31116 ]
 [200.06166 ]
 [132.7116  ]
 [ 99.417854]
 [155.8164  ]
 [124.193504]
 [166.80212 ]
 [157.20898 ]
 [145.0394  ]
 [138.56187 ]
 [186.40244 ]
 [152.05833 ]
 [154.98097 ]
 [184.35794 ]
 [139.29572 ]
 [190.42084 ]
 [179.2954  ]
 [162.13345 ]
 [180.21893 ]
 [170.45859 ]
 [172.40326 ]
 [155.84834 ]
 [186.59042 ]] 


 step:  250 
 Cost:  32.478237 
 Prediction:
 [[158.85901]
 [179.11118]
 [182.30658]
 [200.05777]
 [132.73137]
 [ 99.43841]
 [155.8046 ]
 [124.17124]
 [166.82602]
 [157.23682]
 [145.03806]
 [138.5774 ]
 [186.39734]
 [152.0551 ]
 [154.97481]
 [184.37067]
 [139.30292]
 [190.39873]
 [179.2846 ]
 [162.11996]
 [180.21008]
 [170.47127]
 [172.39136]
 [155.82843]
 [186.59956]] 


 step:  260 
 Cost:  32.331135 
 Prediction:
 [[158.84053 ]
 [179.1261  ]
 [182.30206 ]
 [200.05391 ]
 [132.75111 ]
 [ 99.4589  ]
 [155.79285 ]
 [124.149025]
 [166.84987 ]
 [157.26456 ]
 [145.03671 ]
 [138.59

 [186.78712]] 


 step:  470 
 Cost:  29.438297 
 Prediction:
 [[158.46655]
 [179.42911]
 [182.2113 ]
 [199.97481]
 [133.15279]
 [ 99.87303]
 [155.55147]
 [123.69322]
 [167.3315 ]
 [157.82127]
 [145.00826]
 [138.90428]
 [186.29225]
 [151.99193]
 [154.84071]
 [184.6399 ]
 [139.46284]
 [189.925  ]
 [179.05957]
 [161.83676]
 [180.01935]
 [170.73888]
 [172.13672]
 [155.41167]
 [186.7958 ]] 


 step:  480 
 Cost:  29.309395 
 Prediction:
 [[158.4494  ]
 [179.44307 ]
 [182.20718 ]
 [199.97115 ]
 [133.17133 ]
 [ 99.892006]
 [155.54024 ]
 [123.67202 ]
 [167.35356 ]
 [157.8466  ]
 [145.0069  ]
 [138.9185  ]
 [186.2878  ]
 [151.98938 ]
 [154.83469 ]
 [184.65166 ]
 [139.47018 ]
 [189.90404 ]
 [179.04987 ]
 [161.82448 ]
 [180.01085 ]
 [170.75053 ]
 [172.12547 ]
 [155.39366 ]
 [186.80449 ]] 


 step:  490 
 Cost:  29.181297 
 Prediction:
 [[158.43233 ]
 [179.45699 ]
 [182.20308 ]
 [199.96748 ]
 [133.18982 ]
 [ 99.91091 ]
 [155.52904 ]
 [123.650856]
 [167.37556 ]
 [157.87184 ]
 [145.00554 ]
 [138.93


 step:  700 
 Cost:  26.659279 
 Prediction:
 [[158.08688]
 [179.74   ]
 [182.12097]
 [199.8931 ]
 [133.5667 ]
 [100.29309]
 [155.29933]
 [123.21674]
 [167.82013]
 [158.37892]
 [144.97704]
 [139.21828]
 [186.19617]
 [151.94064]
 [154.70383]
 [184.9001 ]
 [139.63222]
 [189.45506]
 [178.8472 ]
 [161.56656]
 [179.82808]
 [170.99725]
 [171.88464]
 [155.0169 ]
 [186.99023]] 


 step:  710 
 Cost:  26.546806 
 Prediction:
 [[158.07103]
 [179.75305]
 [182.11725]
 [199.88965]
 [133.58409]
 [100.3106 ]
 [155.28865]
 [123.19655]
 [167.84052]
 [158.40201]
 [144.97568]
 [139.23132]
 [186.19229]
 [151.93872]
 [154.69797]
 [184.91095]
 [139.63962]
 [189.4352 ]
 [178.83844]
 [161.55537]
 [179.81995]
 [171.00803]
 [171.87401]
 [155.00063]
 [186.99844]] 


 step:  720 
 Cost:  26.435032 
 Prediction:
 [[158.05525]
 [179.76605]
 [182.11353]
 [199.88622]
 [133.60146]
 [100.32806]
 [155.27798]
 [123.17641]
 [167.86081]
 [158.42499]
 [144.97433]
 [139.24432]
 [186.18842]
 [151.93681]
 [154.6921 ]
 [184.92

 [187.182   ]] 


 step:  950 
 Cost:  24.037167 
 Prediction:
 [[157.70671]
 [180.05481]
 [182.03249]
 [199.80971]
 [133.98773]
 [100.71322]
 [155.03917]
 [122.72474]
 [168.30893]
 [158.92896]
 [144.94322]
 [139.53029]
 [186.10587]
 [151.89975]
 [154.55914]
 [185.16034]
 [139.81737]
 [188.97215]
 [178.64023]
 [161.30005]
 [179.62938]
 [171.25542]
 [171.62617]
 [154.63062]
 [187.18974]] 


 step:  960 
 Cost:  23.94007 
 Prediction:
 [[157.69217 ]
 [180.06693 ]
 [182.02914 ]
 [199.80647 ]
 [134.00397 ]
 [100.72928 ]
 [155.02905 ]
 [122.705605]
 [168.32762 ]
 [158.94981 ]
 [144.94186 ]
 [139.54216 ]
 [186.10252 ]
 [151.89839 ]
 [154.55345 ]
 [185.17027 ]
 [139.82478 ]
 [188.95341 ]
 [178.63243 ]
 [161.28993 ]
 [179.62163 ]
 [171.26527 ]
 [171.61613 ]
 [154.61601 ]
 [187.19748 ]] 


 step:  970 
 Cost:  23.843536 
 Prediction:
 [[157.67769 ]
 [180.07903 ]
 [182.02583 ]
 [199.80327 ]
 [134.02019 ]
 [100.7453  ]
 [155.01898 ]
 [122.686516]
 [168.34625 ]
 [158.9706  ]
 [144.94052 ]
 [139.55

 step:  1190 
 Cost:  21.85561 
 Prediction:
 [[157.37096]
 [180.33603]
 [181.95612]
 [199.73465]
 [134.36557]
 [101.08386]
 [154.80249]
 [122.27675]
 [168.74026]
 [159.40729]
 [144.91106]
 [139.8037 ]
 [186.03143]
 [151.87306]
 [154.4245 ]
 [185.38992]
 [139.99492]
 [188.53447]
 [178.46255]
 [161.0683 ]
 [179.4474 ]
 [171.48294]
 [171.3924 ]
 [154.29752]
 [187.37036]] 


 step:  1200 
 Cost:  21.771149 
 Prediction:
 [[157.35753 ]
 [180.34732 ]
 [181.9531  ]
 [199.7316  ]
 [134.38075 ]
 [101.098656]
 [154.79288 ]
 [122.25859 ]
 [168.75746 ]
 [159.42622 ]
 [144.9097  ]
 [139.81456 ]
 [186.02855 ]
 [151.87216 ]
 [154.41898 ]
 [185.39906 ]
 [140.00227 ]
 [188.51675 ]
 [178.45555 ]
 [161.0591  ]
 [179.44    ]
 [171.49199 ]
 [171.38293 ]
 [154.28436 ]
 [187.37764 ]] 


 step:  1210 
 Cost:  21.68716 
 Prediction:
 [[157.3442 ]
 [180.3586 ]
 [181.9501 ]
 [199.7286 ]
 [134.39594]
 [101.1134 ]
 [154.78333]
 [122.24047]
 [168.77463]
 [159.44511]
 [144.9084 ]
 [139.82541]
 [186.02573]
 [151.871

 step:  1440 
 Cost:  19.882942 
 Prediction:
 [[157.04898 ]
 [180.60873 ]
 [181.88457 ]
 [199.66132 ]
 [134.73355 ]
 [101.4389  ]
 [154.5689  ]
 [121.834335]
 [169.15352 ]
 [159.85884 ]
 [144.878   ]
 [140.06383 ]
 [185.96513 ]
 [151.85646 ]
 [154.28885 ]
 [185.60983 ]
 [140.17856 ]
 [188.10411 ]
 [178.29706 ]
 [160.84949 ]
 [179.26674 ]
 [171.70064 ]
 [171.16296 ]
 [153.98578 ]
 [187.54771 ]] 


 step:  1450 
 Cost:  19.809776 
 Prediction:
 [[157.03667 ]
 [180.61925 ]
 [181.88185 ]
 [199.6585  ]
 [134.74776 ]
 [101.452484]
 [154.55983 ]
 [121.81714 ]
 [169.16933 ]
 [159.87599 ]
 [144.87671 ]
 [140.07375 ]
 [185.9627  ]
 [151.85602 ]
 [154.28352 ]
 [185.61824 ]
 [140.18587 ]
 [188.08742 ]
 [178.29083 ]
 [160.8412  ]
 [179.25969 ]
 [171.70895 ]
 [171.15407 ]
 [153.974   ]
 [187.5546  ]] 


 step:  1460 
 Cost:  19.73702 
 Prediction:
 [[157.0244 ]
 [180.62973]
 [181.87918]
 [199.65567]
 [134.76193]
 [101.46603]
 [154.55078]
 [121.79998]
 [169.1851 ]
 [159.89308]
 [144.87541]
 [140.083

 step:  1660 
 Cost:  18.365662 
 Prediction:
 [[156.78717]
 [180.83289]
 [181.82773]
 [199.60068]
 [135.03723]
 [101.72731]
 [154.37381]
 [121.46458]
 [169.4893 ]
 [160.22052]
 [144.84944]
 [140.27377]
 [185.91519]
 [151.84999]
 [154.17345]
 [185.7885 ]
 [140.33832]
 [187.7459 ]
 [178.1663 ]
 [160.67429]
 [179.11502]
 [171.87732]
 [170.97235]
 [153.73831]
 [187.69524]] 


 step:  1670 
 Cost:  18.301102 
 Prediction:
 [[156.77571]
 [180.84274]
 [181.82526]
 [199.59799]
 [135.05061]
 [101.73991]
 [154.36516]
 [121.4482 ]
 [169.50397]
 [160.2362 ]
 [144.84816]
 [140.28291]
 [185.91309]
 [151.84985]
 [154.16829]
 [185.7963 ]
 [140.34552]
 [187.73004]
 [178.16066]
 [160.66667]
 [179.10828]
 [171.88503]
 [170.96391]
 [153.7276 ]
 [187.70175]] 


 step:  1680 
 Cost:  18.236914 
 Prediction:
 [[156.7643 ]
 [180.85257]
 [181.82281]
 [199.59532]
 [135.06393]
 [101.75249]
 [154.35654]
 [121.43185]
 [169.5186 ]
 [160.25185]
 [144.84686]
 [140.29202]
 [185.91101]
 [151.84972]
 [154.16315]
 [185.

 [187.85359]] 


 step:  1920 
 Cost:  16.800121 
 Prediction:
 [[156.50148 ]
 [181.08    ]
 [181.76712 ]
 [199.53331 ]
 [135.37343 ]
 [102.041626]
 [154.15526 ]
 [121.05015 ]
 [169.85532 ]
 [160.609   ]
 [144.81638 ]
 [140.50105 ]
 [185.86504 ]
 [151.8506  ]
 [154.04192 ]
 [185.98317 ]
 [140.52408 ]
 [187.34587 ]
 [178.0278  ]
 [160.48607 ]
 [178.94417 ]
 [172.06966 ]
 [170.75984 ]
 [153.47487 ]
 [187.85973 ]] 


 step:  1930 
 Cost:  16.744364 
 Prediction:
 [[156.49098]
 [181.08916]
 [181.76494]
 [199.53082]
 [135.3859 ]
 [102.05318]
 [154.14711]
 [121.03469]
 [169.86877]
 [160.62315]
 [144.81512]
 [140.50937]
 [185.8633 ]
 [151.85078]
 [154.03696]
 [185.99034]
 [140.53114]
 [187.331  ]
 [178.0228 ]
 [160.4792 ]
 [178.93777]
 [172.07674]
 [170.75195]
 [153.46533]
 [187.86584]] 


 step:  1940 
 Cost:  16.688902 
 Prediction:
 [[156.48055]
 [181.09828]
 [181.76276]
 [199.52834]
 [135.39833]
 [102.06469]
 [154.13898]
 [121.01925]
 [169.88219]
 [160.63727]
 [144.81387]
 [140.51767]
 [1

### * another way to find out scores (almost the same results as above)

In [15]:
# Lab 4 Multi-variable linear regression

tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['./INFLEARN_Deep_Learning_Zero_To_All/data-01-test-score.csv'],
    shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

## Default values, in case of empty columns. Also specifies the type of the decoded results
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

## Collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

## Placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

## Hypothesis
hypothesis = tf.matmul(X, W) + b

## Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

## Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

## Launch the graph in a session
config = tf.ConfigProto(
    device_count={'GPU': 0} # uncomment this line to force CPU
)
sess = tf.Session(config=config)

## Initailizes global variables in the graph
sess.run(tf.global_variables_initializer())

## Start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                    feed_dict={X:x_batch, Y:y_batch})
    if step % 10 == 0:
        print(' step: ', step, '\n',
              'Cost: ', cost_val,
              '\n Prediction:\n', hy_val, '\n\n')
        
coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

 step:  0 
 Cost:  85162.664 
 Prediction:
 [[-130.61226 ]
 [-156.35466 ]
 [-154.43182 ]
 [-167.38199 ]
 [-119.79308 ]
 [ -87.07731 ]
 [-124.327614]
 [ -90.82258 ]
 [-145.03339 ]
 [-132.5499  ]] 


 step:  10 
 Cost:  5.159034 
 Prediction:
 [[151.67982]
 [182.99113]
 [179.9008 ]
 [196.74463]
 [139.01677]
 [103.7594 ]
 [148.23738]
 [111.24371]
 [172.13853]
 [161.26234]] 


 step:  20 
 Cost:  4.3361783 
 Prediction:
 [[153.58311 ]
 [185.2812  ]
 [182.1558  ]
 [199.20242 ]
 [140.76233 ]
 [105.049614]
 [150.0793  ]
 [112.61216 ]
 [174.2817  ]
 [163.25194 ]] 


 step:  30 
 Cost:  4.355152 
 Prediction:
 [[153.59428]
 [185.29674]
 [182.16986]
 [199.21959]
 [140.77318]
 [105.0607 ]
 [150.09431]
 [112.62625]
 [174.29898]
 [163.27222]] 


 step:  40 
 Cost:  4.3537116 
 Prediction:
 [[153.59268 ]
 [185.29694 ]
 [182.16882 ]
 [199.2203  ]
 [140.77231 ]
 [105.063156]
 [150.097   ]
 [112.63118 ]
 [174.30188 ]
 [163.27917 ]] 


 step:  50 
 Cost:  4.352087 
 Prediction:
 [[153.59099]
 [185.29698

 [163.54533 ]] 


 step:  480 
 Cost:  4.3037148 
 Prediction:
 [[153.52771]
 [185.29726]
 [182.12271]
 [199.24423]
 [140.73073]
 [105.15584]
 [150.203  ]
 [112.83069]
 [174.41087]
 [163.55089]] 


 step:  490 
 Cost:  4.3029757 
 Prediction:
 [[153.52643 ]
 [185.29721 ]
 [182.12177 ]
 [199.24472 ]
 [140.7298  ]
 [105.157684]
 [150.20525 ]
 [112.8349  ]
 [174.41302 ]
 [163.55641 ]] 


 step:  500 
 Cost:  4.3022575 
 Prediction:
 [[153.52515 ]
 [185.29715 ]
 [182.12082 ]
 [199.24524 ]
 [140.72885 ]
 [105.15951 ]
 [150.20747 ]
 [112.839096]
 [174.41519 ]
 [163.5619  ]] 


 step:  510 
 Cost:  4.301554 
 Prediction:
 [[153.52388]
 [185.29709]
 [182.11987]
 [199.24574]
 [140.7279 ]
 [105.16134]
 [150.2097 ]
 [112.8433 ]
 [174.41733]
 [163.56738]] 


 step:  520 
 Cost:  4.300846 
 Prediction:
 [[153.5226  ]
 [185.29701 ]
 [182.11894 ]
 [199.24623 ]
 [140.72697 ]
 [105.163155]
 [150.21191 ]
 [112.84748 ]
 [174.41946 ]
 [163.57285 ]] 


 step:  530 
 Cost:  4.3001933 
 Prediction:
 [[153.52

 step:  970 
 Cost:  4.282386 
 Prediction:
 [[153.47328]
 [185.29218]
 [182.08107]
 [199.26726]
 [140.68529]
 [105.2346 ]
 [150.3048 ]
 [113.02263]
 [174.5035 ]
 [163.79305]] 


 step:  980 
 Cost:  4.2822175 
 Prediction:
 [[153.47235]
 [185.29202]
 [182.08032]
 [199.2677 ]
 [140.68437]
 [105.23597]
 [150.3067 ]
 [113.02624]
 [174.50513]
 [163.7974 ]] 


 step:  990 
 Cost:  4.2820396 
 Prediction:
 [[153.4714  ]
 [185.29189 ]
 [182.07957 ]
 [199.26813 ]
 [140.68347 ]
 [105.23734 ]
 [150.30862 ]
 [113.029854]
 [174.50676 ]
 [163.80176 ]] 


 step:  1000 
 Cost:  4.281882 
 Prediction:
 [[153.47049 ]
 [185.29173 ]
 [182.07883 ]
 [199.26857 ]
 [140.68257 ]
 [105.2387  ]
 [150.31053 ]
 [113.033455]
 [174.50836 ]
 [163.8061  ]] 


 step:  1010 
 Cost:  4.2817407 
 Prediction:
 [[153.46956]
 [185.2916 ]
 [182.07808]
 [199.26901]
 [140.68166]
 [105.24006]
 [150.31244]
 [113.03704]
 [174.50996]
 [163.8104 ]] 


 step:  1020 
 Cost:  4.281602 
 Prediction:
 [[153.46864]
 [185.29143]
 [182.07

 step:  1450 
 Cost:  4.281503 
 Prediction:
 [[153.43434]
 [185.28336]
 [182.04836]
 [199.2867 ]
 [140.6424 ]
 [105.29211]
 [150.3904 ]
 [113.18435]
 [174.57124]
 [163.98074]] 


 step:  1460 
 Cost:  4.2815924 
 Prediction:
 [[153.43364]
 [185.28314]
 [182.04773]
 [199.28705]
 [140.64153]
 [105.29314]
 [150.39203]
 [113.18747]
 [174.57243]
 [163.98419]] 


 step:  1470 
 Cost:  4.281725 
 Prediction:
 [[153.43295 ]
 [185.28291 ]
 [182.04712 ]
 [199.28743 ]
 [140.64064 ]
 [105.29416 ]
 [150.39368 ]
 [113.190575]
 [174.57362 ]
 [163.98764 ]] 


 step:  1480 
 Cost:  4.281857 
 Prediction:
 [[153.43228]
 [185.28271]
 [182.04652]
 [199.28781]
 [140.63979]
 [105.29517]
 [150.39532]
 [113.19369]
 [174.57483]
 [163.99109]] 


 step:  1490 
 Cost:  4.2819757 
 Prediction:
 [[153.4316 ]
 [185.28249]
 [182.04591]
 [199.28818]
 [140.6389 ]
 [105.29617]
 [150.39696]
 [113.19677]
 [174.576  ]
 [163.99449]] 


 step:  1500 
 Cost:  4.282096 
 Prediction:
 [[153.43094 ]
 [185.28226 ]
 [182.0453  ]


 step:  1930 
 Cost:  4.290932 
 Prediction:
 [[153.40628 ]
 [185.27197 ]
 [182.02194 ]
 [199.30344 ]
 [140.60156 ]
 [105.334526]
 [150.4641  ]
 [113.32392 ]
 [174.6212  ]
 [164.12936 ]] 


 step:  1940 
 Cost:  4.2911987 
 Prediction:
 [[153.40579 ]
 [185.27171 ]
 [182.02147 ]
 [199.30376 ]
 [140.60074 ]
 [105.33527 ]
 [150.46552 ]
 [113.326614]
 [174.62209 ]
 [164.13213 ]] 


 step:  1950 
 Cost:  4.291453 
 Prediction:
 [[153.4053  ]
 [185.27145 ]
 [182.02097 ]
 [199.3041  ]
 [140.59991 ]
 [105.336006]
 [150.46693 ]
 [113.32931 ]
 [174.62296 ]
 [164.13483 ]] 


 step:  1960 
 Cost:  4.2917185 
 Prediction:
 [[153.40483]
 [185.2712 ]
 [182.0205 ]
 [199.3044 ]
 [140.59909]
 [105.33675]
 [150.46834]
 [113.33198]
 [174.62383]
 [164.13754]] 


 step:  1970 
 Cost:  4.292011 
 Prediction:
 [[153.40436]
 [185.27094]
 [182.02   ]
 [199.30475]
 [140.59827]
 [105.33749]
 [150.46976]
 [113.33466]
 [174.6247 ]
 [164.14026]] 


 step:  1980 
 Cost:  4.292257 
 Prediction:
 [[153.40388]
 [185.270

### ~ Section 4