### * https://www.inflearn.com/course-status-2/ (Section 4)

In [1]:
import tensorflow as tf

## * multi-variable linear regression

In [7]:
## Load data
x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data =[152, 185, 180, 196, 142]

## Placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

## random_normal is ([1]) because each weight is one(a) value
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b

## cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

## Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

## Launch the graph in a session
sess = tf.Session()
## Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict={x1:x1_data,
                                               x2:x2_data,
                                               x3:x3_data,
                                               Y:y_data})
    if step % 20 == 0:
        print(' step: ', step, '\n', "Cost: ", cost_val, "\n Prediction:\n", hy_val, '\n\n')

 step:  0 
 Cost:  52521.82 
 Prediction:
 [-50.2805   -61.183556 -60.135323 -62.41191  -49.425297] 


 step:  20 
 Cost:  8.840517 
 Prediction:
 [153.03221 183.2148  180.65823 199.8062  136.99702] 


 step:  40 
 Cost:  8.782776 
 Prediction:
 [153.0175  183.22858 180.6556  199.80327 137.01543] 


 step:  60 
 Cost:  8.72562 
 Prediction:
 [153.001   183.24007 180.65079 199.79797 137.03204] 


 step:  80 
 Cost:  8.669077 
 Prediction:
 [152.98465 183.25148 180.64601 199.7927  137.04857] 


 step:  100 
 Cost:  8.613058 
 Prediction:
 [152.96832 183.26283 180.64124 199.78741 137.065  ] 


 step:  120 
 Cost:  8.557646 
 Prediction:
 [152.95212 183.27412 180.6365  199.78218 137.08136] 


 step:  140 
 Cost:  8.502805 
 Prediction:
 [152.93602 183.28535 180.63182 199.77698 137.09764] 


 step:  160 
 Cost:  8.448523 
 Prediction:
 [152.92    183.29652 180.62714 199.77177 137.11382] 


 step:  180 
 Cost:  8.394717 
 Prediction:
 [152.90407 183.30763 180.62248 199.76657 137.12993] 


 s

 step:  1680 
 Cost:  5.575535 
 Prediction:
 [151.93504 183.98546 180.34279 199.43047 138.13237] 


 step:  1700 
 Cost:  5.5501966 
 Prediction:
 [151.92474 183.99272 180.33986 199.4266  138.14337] 


 step:  1720 
 Cost:  5.5251484 
 Prediction:
 [151.9145  183.99991 180.33694 199.42276 138.1543 ] 


 step:  1740 
 Cost:  5.5003347 
 Prediction:
 [151.90431 184.00705 180.33405 199.4189  138.16515] 


 step:  1760 
 Cost:  5.475729 
 Prediction:
 [151.8942  184.01419 180.33118 199.41507 138.17596] 


 step:  1780 
 Cost:  5.451358 
 Prediction:
 [151.88412 184.02126 180.32831 199.41125 138.18674] 


 step:  1800 
 Cost:  5.4272356 
 Prediction:
 [151.87411 184.02827 180.32545 199.40744 138.19743] 


 step:  1820 
 Cost:  5.4033194 
 Prediction:
 [151.86417 184.0353  180.32265 199.40366 138.2081 ] 


 step:  1840 
 Cost:  5.379651 
 Prediction:
 [151.85428 184.04225 180.31985 199.39989 138.2187 ] 


 step:  1860 
 Cost:  5.3562155 
 Prediction:
 [151.84445 184.04918 180.31706 199.3961

In [9]:
## Load data
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

## Placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

## Hypothesis
hypothesis = tf.matmul(X, W) + b
## Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
## Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

## Launch the graph in a session
sess = tf.Session()
## Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict={X:x_data, Y:y_data})
    if step % 20 == 0:
        print(' step: ', step, '\n',
              'Cost: ', cost,
              '\n Prediction:\n', hy_val, '\n\n')

 step:  0 
 Cost:  Tensor("Mean_6:0", dtype=float32) 
 Prediction:
 [[32.48174 ]
 [48.302303]
 [43.030987]
 [47.436504]
 [38.097214]] 


 step:  20 
 Cost:  Tensor("Mean_6:0", dtype=float32) 
 Prediction:
 [[147.89644]
 [186.99127]
 [179.6997 ]
 [196.26288]
 [143.87631]] 


 step:  40 
 Cost:  Tensor("Mean_6:0", dtype=float32) 
 Prediction:
 [[147.9138 ]
 [186.98141]
 [179.70602]
 [196.26733]
 [143.86316]] 


 step:  60 
 Cost:  Tensor("Mean_6:0", dtype=float32) 
 Prediction:
 [[147.93004]
 [186.97037]
 [179.71109]
 [196.27043]
 [143.84915]] 


 step:  80 
 Cost:  Tensor("Mean_6:0", dtype=float32) 
 Prediction:
 [[147.94614]
 [186.95935]
 [179.7161 ]
 [196.27347]
 [143.83517]] 


 step:  100 
 Cost:  Tensor("Mean_6:0", dtype=float32) 
 Prediction:
 [[147.9622 ]
 [186.9484 ]
 [179.72107]
 [196.2765 ]
 [143.8213 ]] 


 step:  120 
 Cost:  Tensor("Mean_6:0", dtype=float32) 
 Prediction:
 [[147.97815]
 [186.93752]
 [179.72603]
 [196.27951]
 [143.8075 ]] 


 step:  140 
 Cost:  Tensor("Mean

 step:  1220 
 Cost:  Tensor("Mean_6:0", dtype=float32) 
 Prediction:
 [[148.73705]
 [186.42041]
 [179.96251]
 [196.41957]
 [143.15514]] 


 step:  1240 
 Cost:  Tensor("Mean_6:0", dtype=float32) 
 Prediction:
 [[148.7489 ]
 [186.41234]
 [179.96622]
 [196.4217 ]
 [143.14503]] 


 step:  1260 
 Cost:  Tensor("Mean_6:0", dtype=float32) 
 Prediction:
 [[148.76068]
 [186.40433]
 [179.9699 ]
 [196.42381]
 [143.13496]] 


 step:  1280 
 Cost:  Tensor("Mean_6:0", dtype=float32) 
 Prediction:
 [[148.7724 ]
 [186.39633]
 [179.97354]
 [196.4259 ]
 [143.12498]] 


 step:  1300 
 Cost:  Tensor("Mean_6:0", dtype=float32) 
 Prediction:
 [[148.78406]
 [186.38841]
 [179.97719]
 [196.428  ]
 [143.11504]] 


 step:  1320 
 Cost:  Tensor("Mean_6:0", dtype=float32) 
 Prediction:
 [[148.79565]
 [186.38051]
 [179.98082]
 [196.43005]
 [143.10515]] 


 step:  1340 
 Cost:  Tensor("Mean_6:0", dtype=float32) 
 Prediction:
 [[148.8072 ]
 [186.3727 ]
 [179.98445]
 [196.43213]
 [143.09532]] 


 step:  1360 
 Cost:

### * Retrieve data from a file as Tensorflow

In [10]:
import numpy as np

In [36]:
xy = np.loadtxt('./INFLEARN_Deep_Learning_Zero_To_All/data-01-test-score.csv',
                delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [37]:
## Make sure the shape and data are OK
print(xy.shape, '\n')
print(x_data.shape, '\n', x_data, '\n', len(x_data), '\n')
print(y_data.shape, '\n', y_data, '\n', len(y_data))

(25, 4) 

(25, 3) 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
 25 

(25, 1) 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
 25


In [39]:
## Placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

## Hypothesis
hypothesis = tf.matmul(X, W) + b

## Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

## Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

## Launch the graph in a session
sess = tf.Session()
## Initailizes global variables in the graph
sess.run(tf.global_variables_initializer())

## Set up feed_dict variables inside the loop
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict={X:x_data, Y:y_data})
    if step % 10 == 0:
        print(' step: ', step, '\n',
              'Cost: ', cost_val,
              '\n Prediction:\n', hy_val, '\n\n')

## Ask my score
print("Your score will be ", sess.run(hypothesis,
                                      feed_dict={X:[[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X:[[60, 70, 100], 
                                                      [90, 100, 80]]}))

 step:  0 
 Cost:  5181.1675 
 Prediction:
 [[ 81.52373 ]
 [105.12589 ]
 [ 99.53846 ]
 [111.21802 ]
 [ 79.92297 ]
 [ 64.6804  ]
 [ 85.8792  ]
 [ 66.993706]
 [103.64481 ]
 [103.25336 ]
 [ 81.987144]
 [ 85.25942 ]
 [ 99.915535]
 [ 79.590546]
 [ 87.700676]
 [108.77035 ]
 [ 74.602425]
 [102.92397 ]
 [ 93.70983 ]
 [ 83.72227 ]
 [100.49068 ]
 [101.09794 ]
 [ 94.40801 ]
 [ 75.46187 ]
 [106.35294 ]] 


 step:  10 
 Cost:  20.383396 
 Prediction:
 [[148.62082]
 [185.74248]
 [178.9863 ]
 [197.7352 ]
 [141.40555]
 [109.99406]
 [150.63692]
 [114.99718]
 [178.97102]
 [173.00453]
 [144.37729]
 [146.7622 ]
 [182.0034 ]
 [147.83852]
 [152.75104]
 [190.5726 ]
 [139.60017]
 [180.64125]
 [171.97438]
 [153.75201]
 [176.42804]
 [176.72151]
 [166.81284]
 [143.12877]
 [189.91066]] 


 step:  20 
 Cost:  20.015762 
 Prediction:
 [[149.10123 ]
 [186.29199 ]
 [179.54272 ]
 [198.33372 ]
 [141.82385 ]
 [110.28767 ]
 [151.08168 ]
 [115.323166]
 [179.46898 ]
 [173.44678 ]
 [144.80513 ]
 [147.16887 ]
 [182.5854  ]
 

 step:  300 
 Cost:  17.021605 
 Prediction:
 [[149.55095]
 [186.0978 ]
 [179.74614]
 [198.35957]
 [141.65443]
 [109.77469]
 [151.01599]
 [115.17737]
 [178.87785]
 [172.40083]
 [144.72375]
 [146.68933]
 [182.98291]
 [148.89172]
 [152.99544]
 [190.81004]
 [140.61311]
 [181.14482]
 [173.05794]
 [154.76717]
 [176.83551]
 [176.90535]
 [167.32387]
 [144.52298]
 [190.49431]] 


 step:  310 
 Cost:  16.927826 
 Prediction:
 [[149.56589]
 [186.09114]
 [179.75282]
 [198.36032]
 [141.6486 ]
 [109.75743]
 [151.0137 ]
 [115.17247]
 [178.85791]
 [172.36569]
 [144.72093]
 [146.67316]
 [182.99606]
 [148.91034]
 [152.98874]
 [190.79932]
 [140.63113]
 [181.14368]
 [173.0753 ]
 [154.78418]
 [176.83163]
 [176.89429]
 [167.32411]
 [144.55275]
 [190.49434]] 


 step:  320 
 Cost:  16.834854 
 Prediction:
 [[149.5808  ]
 [186.08452 ]
 [179.75946 ]
 [198.36105 ]
 [141.64284 ]
 [109.74024 ]
 [151.01146 ]
 [115.167595]
 [178.83809 ]
 [172.33073 ]
 [144.71814 ]
 [146.65707 ]
 [183.00917 ]
 [148.9289  ]
 [152.98

 step:  610 
 Cost:  14.467933 
 Prediction:
 [[149.98578]
 [185.90396]
 [179.93999]
 [198.38113]
 [141.48476]
 [109.27304]
 [150.951  ]
 [115.03703]
 [178.29869]
 [171.38106]
 [144.64224]
 [146.21999]
 [183.36464]
 [149.43173]
 [152.80211]
 [190.49886]
 [141.13518]
 [181.11333]
 [173.56233]
 [155.26154]
 [176.72403]
 [176.58426]
 [167.33232]
 [145.38722]
 [190.4952 ]] 


 step:  620 
 Cost:  14.396683 
 Prediction:
 [[149.99886 ]
 [185.89812 ]
 [179.94582 ]
 [198.38179 ]
 [141.47963 ]
 [109.257965]
 [150.94908 ]
 [115.0329  ]
 [178.2813  ]
 [171.35043 ]
 [144.6398  ]
 [146.2059  ]
 [183.37608 ]
 [149.44792 ]
 [152.79634 ]
 [190.4895  ]
 [141.1508  ]
 [181.11246 ]
 [173.57747 ]
 [155.27638 ]
 [176.72072 ]
 [176.5746  ]
 [167.33261 ]
 [145.41316 ]
 [190.4952  ]] 


 step:  630 
 Cost:  14.326056 
 Prediction:
 [[150.01187 ]
 [185.89229 ]
 [179.95161 ]
 [198.38246 ]
 [141.47452 ]
 [109.24294 ]
 [150.94717 ]
 [115.028755]
 [178.26396 ]
 [171.31996 ]
 [144.63737 ]
 [146.19186 ]
 [183.3875 

 step:  880 
 Cost:  12.749039 
 Prediction:
 [[150.3196  ]
 [185.75441 ]
 [180.08842 ]
 [198.39803 ]
 [141.3531  ]
 [108.887985]
 [150.90273 ]
 [114.93245 ]
 [177.85417 ]
 [170.59993 ]
 [144.58018 ]
 [145.86018 ]
 [183.65646 ]
 [149.84409 ]
 [152.6553  ]
 [190.26003 ]
 [141.53267 ]
 [181.09181 ]
 [173.94838 ]
 [155.64024 ]
 [176.64    ]
 [176.33788 ]
 [167.34013 ]
 [146.04883 ]
 [190.49486 ]] 


 step:  890 
 Cost:  12.692949 
 Prediction:
 [[150.33124 ]
 [185.74919 ]
 [180.09358 ]
 [198.39862 ]
 [141.3485  ]
 [108.87458 ]
 [150.90108 ]
 [114.928856]
 [177.83868 ]
 [170.57275 ]
 [144.57803 ]
 [145.84766 ]
 [183.66661 ]
 [149.8584  ]
 [152.65022 ]
 [190.25171 ]
 [141.54646 ]
 [181.0911  ]
 [173.96179 ]
 [155.65341 ]
 [176.63708 ]
 [176.3293  ]
 [167.34042 ]
 [146.07184 ]
 [190.49481 ]] 


 step:  900 
 Cost:  12.63732 
 Prediction:
 [[150.34282]
 [185.744  ]
 [180.09874]
 [198.39922]
 [141.3439 ]
 [108.86122]
 [150.89943]
 [114.92529]
 [177.82329]
 [170.54568]
 [144.5759 ]
 [145.83519]

 [190.49367]] 


 step:  1160 
 Cost:  11.351537 
 Prediction:
 [[150.62686 ]
 [185.61609 ]
 [180.22466 ]
 [198.4139  ]
 [141.23062 ]
 [108.53363 ]
 [150.85977 ]
 [114.839035]
 [177.44508 ]
 [169.88254 ]
 [144.52356 ]
 [145.52943 ]
 [183.92393 ]
 [150.2216  ]
 [152.52165 ]
 [190.04027 ]
 [141.89551 ]
 [181.07439 ]
 [174.30261 ]
 [155.98802 ]
 [176.56401 ]
 [176.1112  ]
 [167.3485  ]
 [146.65604 ]
 [190.4936  ]] 


 step:  1170 
 Cost:  11.307768 
 Prediction:
 [[150.63716]
 [185.61143]
 [180.22922]
 [198.41444]
 [141.22649]
 [108.52176]
 [150.85835]
 [114.83595]
 [177.43138]
 [169.85854]
 [144.52165]
 [145.51836]
 [183.93288]
 [150.2342 ]
 [152.5172 ]
 [190.0329 ]
 [141.90761]
 [181.07384]
 [174.31445]
 [155.99965]
 [176.56151]
 [176.1036 ]
 [167.3488 ]
 [146.67635]
 [190.49356]] 


 step:  1180 
 Cost:  11.264364 
 Prediction:
 [[150.64742]
 [185.60681]
 [180.23375]
 [198.41498]
 [141.22238]
 [108.50993]
 [150.85696]
 [114.8329 ]
 [177.41774]
 [169.83461]
 [144.51979]
 [145.50734]
 [1

 step:  1440 
 Cost:  10.260839 
 Prediction:
 [[150.899  ]
 [185.49294]
 [180.34497]
 [198.42824]
 [141.12091]
 [108.21982]
 [150.82314]
 [114.75901]
 [177.08284]
 [169.24864]
 [144.47385]
 [145.23692]
 [184.15977]
 [150.55403]
 [152.40465]
 [189.84569]
 [142.21402]
 [181.06123]
 [174.61533]
 [156.2953 ]
 [176.49806]
 [175.91054]
 [167.35701]
 [147.19221]
 [190.49162]] 


 step:  1450 
 Cost:  10.22667 
 Prediction:
 [[150.90811]
 [185.48878]
 [180.34898]
 [198.42873]
 [141.1172 ]
 [108.2093 ]
 [150.82191]
 [114.75637]
 [177.0707 ]
 [169.22742]
 [144.47218]
 [145.22713]
 [184.16765]
 [150.56514]
 [152.40074]
 [189.83914]
 [142.22464]
 [181.0608 ]
 [174.62578]
 [156.30559]
 [176.49586]
 [175.90382]
 [167.35732]
 [147.21014]
 [190.49155]] 


 step:  1460 
 Cost:  10.1928005 
 Prediction:
 [[150.91719]
 [185.48466]
 [180.353  ]
 [198.42921]
 [141.11351]
 [108.19883]
 [150.82072]
 [114.75375]
 [177.05861]
 [169.2063 ]
 [144.47054]
 [145.21736]
 [184.17549]
 [150.5762 ]
 [152.39687]
 [189.

 [190.48918]] 


 step:  1720 
 Cost:  9.409462 
 Prediction:
 [[151.14009 ]
 [185.38324 ]
 [180.45123 ]
 [198.44125 ]
 [141.02258 ]
 [107.941864]
 [150.79198 ]
 [114.690636]
 [176.76201 ]
 [168.6885  ]
 [144.43024 ]
 [144.97818 ]
 [184.36769 ]
 [150.84677 ]
 [152.30229 ]
 [189.67336 ]
 [142.49353 ]
 [181.05168 ]
 [174.89139 ]
 [156.56685 ]
 [176.44084 ]
 [175.73288 ]
 [167.3656  ]
 [147.66566 ]
 [190.48907 ]] 


 step:  1730 
 Cost:  9.382776 
 Prediction:
 [[151.14816 ]
 [185.37955 ]
 [180.45479 ]
 [198.4417  ]
 [141.01927 ]
 [107.93255 ]
 [150.79095 ]
 [114.688385]
 [176.75125 ]
 [168.66975 ]
 [144.42877 ]
 [144.96951 ]
 [184.37465 ]
 [150.85654 ]
 [152.29887 ]
 [189.66759 ]
 [142.50285 ]
 [181.0514  ]
 [174.90062 ]
 [156.57594 ]
 [176.43895 ]
 [175.72691 ]
 [167.3659  ]
 [147.6815  ]
 [190.48897 ]] 


 step:  1740 
 Cost:  9.356323 
 Prediction:
 [[151.15622]
 [185.37589]
 [180.45834]
 [198.44214]
 [141.01596]
 [107.92327]
 [150.78995]
 [114.68615]
 [176.74057]
 [168.6511 ]
 [144.4

 step:  1940 
 Cost:  8.873722 
 Prediction:
 [[151.31006]
 [185.30551]
 [180.52594]
 [198.4506 ]
 [140.95251]
 [107.74592]
 [150.77087]
 [114.64408]
 [176.53586]
 [168.2945 ]
 [144.39978]
 [144.79602]
 [184.51364]
 [151.05197]
 [152.23099]
 [189.55191]
 [142.68884]
 [181.04636]
 [175.08542]
 [156.75786]
 [176.40134]
 [175.60768]
 [167.37234]
 [147.99847]
 [190.48672]] 


 step:  1950 
 Cost:  8.851746 
 Prediction:
 [[151.31741 ]
 [185.30214 ]
 [180.52917 ]
 [198.451   ]
 [140.94946 ]
 [107.73744 ]
 [150.76997 ]
 [114.642105]
 [176.52606 ]
 [168.27748 ]
 [144.39847 ]
 [144.78815 ]
 [184.51993 ]
 [151.06082 ]
 [152.2279  ]
 [189.54666 ]
 [142.69725 ]
 [181.04616 ]
 [175.09378 ]
 [156.76611 ]
 [176.39963 ]
 [175.60226 ]
 [167.37265 ]
 [148.01285 ]
 [190.4866  ]] 


 step:  1960 
 Cost:  8.829976 
 Prediction:
 [[151.32474 ]
 [185.29878 ]
 [180.53238 ]
 [198.45142 ]
 [140.94641 ]
 [107.72901 ]
 [150.76909 ]
 [114.640144]
 [176.51634 ]
 [168.26054 ]
 [144.39716 ]
 [144.7803  ]
 [184.5262 

In [47]:
filename_queue = tf.train.string_input_producer(['./INFLEARN_Deep_Learning_Zero_To_All/data-01-test-score.csv'],
                                                shuffle=False, name='filename_queue')

In [48]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

In [49]:
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [ ]:
## Collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]],
                                              batch_size=10)

## Placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

## Hypothesis
hypothesis = tf.matmul(X, W) + b

## Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

## Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

## Launch the graph in a session
sess = tf.Session()
## Initailizes global variables in the graph
sess.run(tf.global_variables_initializer())

## Start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                    feed_dict={X:x_batch, Y:y_batch})
    if step % 10 == 0:
        print(' step: ', step, '\n',
              'Cost: ', cost_val, '\n',
              '\n Prediction:\n', hy_val)
        
coord.request_stop()
coord.join(threads)