### * https://www.inflearn.com/course-status-2/ (Section 4)

In [1]:
import tensorflow as tf

## * multi-variable linear regression

In [2]:
## Load data
x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data =[152, 185, 180, 196, 142]

## Placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

## random_normal is ([1]) because each weight is one(a) value
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b

## cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

## Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

## Launch the graph in a session
sess = tf.Session()
## Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict={x1:x1_data,
                                               x2:x2_data,
                                               x3:x3_data,
                                               Y:y_data})
    if step % 20 == 0:
        print(' step: ', step, '\n', "Cost: ", cost_val, "\n Prediction:\n", hy_val, '\n\n')

 step:  0 
 Cost:  100690.47 
 Prediction:
 [-123.39799 -158.42076 -151.00749 -164.00089 -123.52564] 


 step:  20 
 Cost:  26.40686 
 Prediction:
 [158.0793  179.96782 182.37419 199.04695 134.59508] 


 step:  40 
 Cost:  26.130625 
 Prediction:
 [158.043   179.99767 182.36542 199.04091 134.63321] 


 step:  60 
 Cost:  25.857342 
 Prediction:
 [158.00432 180.02426 182.35368 199.03162 134.66881] 


 step:  80 
 Cost:  25.587011 
 Prediction:
 [157.96585 180.05072 182.34201 199.02237 134.70421] 


 step:  100 
 Cost:  25.319561 
 Prediction:
 [157.9276  180.07704 182.3304  199.01317 134.73943] 


 step:  120 
 Cost:  25.055088 
 Prediction:
 [157.88954 180.10318 182.31883 199.00397 134.77441] 


 step:  140 
 Cost:  24.79341 
 Prediction:
 [157.85172 180.12921 182.30734 198.99486 134.80925] 


 step:  160 
 Cost:  24.534573 
 Prediction:
 [157.81407 180.15508 182.29591 198.9858  134.84389] 


 step:  180 
 Cost:  24.278389 
 Prediction:
 [157.77664 180.18083 182.28455 198.97675 134.878

 step:  1700 
 Cost:  11.075752 
 Prediction:
 [155.45602 181.77779 181.58119 198.40799 137.02472] 


 step:  1720 
 Cost:  10.964265 
 Prediction:
 [155.43146 181.79471 181.57379 198.40186 137.04755] 


 step:  1740 
 Cost:  10.853982 
 Prediction:
 [155.40707 181.81152 181.5664  198.39575 137.07028] 


 step:  1760 
 Cost:  10.744852 
 Prediction:
 [155.38277 181.82823 181.55905 198.38965 137.09286] 


 step:  1780 
 Cost:  10.636912 
 Prediction:
 [155.35863 181.84486 181.55174 198.38359 137.11534] 


 step:  1800 
 Cost:  10.530142 
 Prediction:
 [155.33461 181.8614  181.54448 198.37758 137.1377 ] 


 step:  1820 
 Cost:  10.424518 
 Prediction:
 [155.31073 181.87785 181.53728 198.37157 137.15993] 


 step:  1840 
 Cost:  10.320009 
 Prediction:
 [155.28697 181.89421 181.53009 198.36562 137.18205] 


 step:  1860 
 Cost:  10.216628 
 Prediction:
 [155.26335 181.91048 181.52296 198.35966 137.20406] 


 step:  1880 
 Cost:  10.114317 
 Prediction:
 [155.23985 181.92668 181.51587 198.

In [3]:
## Load data
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

## Placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

## Hypothesis
hypothesis = tf.matmul(X, W) + b
## Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
## Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

## Launch the graph in a session
sess = tf.Session()
## Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict={X:x_data, Y:y_data})
    if step % 20 == 0:
        print(' step: ', step, '\n',
              'Cost: ', cost,
              '\n Prediction:\n', hy_val, '\n\n')

 step:  0 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[-4.581658 ]
 [14.906035 ]
 [ 3.880851 ]
 [ 6.9830623]
 [14.302588 ]] 


 step:  20 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[141.97037]
 [190.96158]
 [177.3978 ]
 [195.93228]
 [148.57178]] 


 step:  40 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[142.01869]
 [190.9311 ]
 [177.41393]
 [195.9435 ]
 [148.53175]] 


 step:  60 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[142.06541]
 [190.89917]
 [177.42834]
 [195.95291]
 [148.49072]] 


 step:  80 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[142.1119 ]
 [190.86742]
 [177.44273]
 [195.96227]
 [148.44994]] 


 step:  100 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[142.15813]
 [190.83582]
 [177.45703]
 [195.97156]
 [148.40936]] 


 step:  120 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[142.20412]
 [190.80443]
 [177.47128]
 [195.98083]
 [148.36902]] 


 step:  140 
 Cost:  Tensor(

 step:  1180 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[144.31969]
 [189.3596 ]
 [178.12648]
 [196.40047]
 [146.51886]] 


 step:  1200 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[144.3541 ]
 [189.3361 ]
 [178.13715]
 [196.40717]
 [146.48888]] 


 step:  1220 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[144.38834]
 [189.31271]
 [178.14777]
 [196.41385]
 [146.45908]] 


 step:  1240 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[144.42241]
 [189.2895 ]
 [178.15836]
 [196.42047]
 [146.42943]] 


 step:  1260 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[144.45628]
 [189.26636]
 [178.16885]
 [196.42706]
 [146.39993]] 


 step:  1280 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[144.48997]
 [189.24336]
 [178.1793 ]
 [196.43361]
 [146.3706 ]] 


 step:  1300 
 Cost:  Tensor("Mean_1:0", dtype=float32) 
 Prediction:
 [[144.5235 ]
 [189.22049]
 [178.18971]
 [196.44012]
 [146.34145]] 


 step:  1320 
 Cost:

### * Retrieve data from a file as Tensorflow

In [4]:
import numpy as np

In [5]:
xy = np.loadtxt('./INFLEARN_Deep_Learning_Zero_To_All/data-01-test-score.csv',
                delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [6]:
## Make sure the shape and data are OK
print(xy.shape, '\n')
print(x_data.shape, '\n', x_data, '\n', len(x_data), '\n')
print(y_data.shape, '\n', y_data, '\n', len(y_data))

(25, 4) 

(25, 3) 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
 25 

(25, 1) 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
 25


In [14]:
tf.set_random_seed(777)  # for reproducibility

## Placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

## Hypothesis
hypothesis = tf.matmul(X, W) + b

## Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

## Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

## Launch the graph in a session
sess = tf.Session()
## Initailizes global variables in the graph
sess.run(tf.global_variables_initializer())

## Set up feed_dict variables inside the loop
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict={X:x_data, Y:y_data})
    if step % 10 == 0:
        print(' step: ', step, '\n',
              'Cost: ', cost_val,
              '\n Prediction:\n', hy_val, '\n\n')

## Ask my score
print("Your score will be ", sess.run(hypothesis,
                                      feed_dict={X:[[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X:[[60, 70, 100], 
                                                      [90, 100, 80]]}))

 step:  0 
 Cost:  173258.62 
 Prediction:
 [[-237.06432]
 [-283.16925]
 [-279.6297 ]
 [-306.93997]
 [-213.74554]
 [-161.4891 ]
 [-234.13353]
 [-179.65147]
 [-267.37872]
 [-253.08499]
 [-222.58774]
 [-219.75099]
 [-286.28287]
 [-234.47302]
 [-235.24635]
 [-289.8538 ]
 [-219.83965]
 [-282.73038]
 [-272.8197 ]
 [-244.8303 ]
 [-273.28476]
 [-268.2407 ]
 [-260.02274]
 [-233.03368]
 [-292.50772]] 


 step:  10 
 Cost:  63.12753 
 Prediction:
 [[151.52734]
 [183.89677]
 [180.56934]
 [194.26556]
 [142.46059]
 [101.15031]
 [141.0529 ]
 [ 98.51161]
 [169.1481 ]
 [151.27704]
 [138.87512]
 [136.67082]
 [189.1524 ]
 [160.73401]
 [141.6684 ]
 [184.12022]
 [156.53082]
 [167.53535]
 [180.43535]
 [160.7259 ]
 [166.67801]
 [169.94249]
 [159.44191]
 [158.72702]
 [191.54333]] 


 step:  20 
 Cost:  54.51295 
 Prediction:
 [[154.19885 ]
 [187.12163 ]
 [183.7385  ]
 [197.73126 ]
 [144.91177 ]
 [102.981094]
 [143.66437 ]
 [100.47137 ]
 [172.18259 ]
 [154.12047 ]
 [141.38065 ]
 [139.15294 ]
 [192.4122  ]
 [1

 step:  280 
 Cost:  46.350883 
 Prediction:
 [[153.89726 ]
 [187.08589 ]
 [183.50604 ]
 [197.82932 ]
 [144.676   ]
 [103.38763 ]
 [144.1687  ]
 [101.437965]
 [172.65431 ]
 [155.3632  ]
 [141.60316 ]
 [139.6513  ]
 [191.81746 ]
 [162.4489  ]
 [144.88988 ]
 [187.67354 ]
 [157.82565 ]
 [171.42665 ]
 [182.86548 ]
 [162.92986 ]
 [170.25055 ]
 [173.26964 ]
 [162.71487 ]
 [160.25847 ]
 [194.62239 ]] 


 step:  290 
 Cost:  46.068066 
 Prediction:
 [[153.8859  ]
 [187.08351 ]
 [183.49681 ]
 [197.83208 ]
 [144.66643 ]
 [103.401634]
 [144.18665 ]
 [101.47313 ]
 [172.67033 ]
 [155.40735 ]
 [141.61067 ]
 [139.6686  ]
 [191.795   ]
 [162.41266 ]
 [144.911   ]
 [187.68228 ]
 [157.7791  ]
 [171.45366 ]
 [182.84029 ]
 [162.90845 ]
 [170.26865 ]
 [173.27917 ]
 [162.72752 ]
 [160.21695 ]
 [194.61209 ]] 


 step:  300 
 Cost:  45.787308 
 Prediction:
 [[153.8746  ]
 [187.08112 ]
 [183.48767 ]
 [197.83484 ]
 [144.65686 ]
 [103.41557 ]
 [144.20454 ]
 [101.508194]
 [172.68628 ]
 [155.45132 ]
 [141.61815 ]


 step:  530 
 Cost:  39.881622 
 Prediction:
 [[153.63261]
 [187.02353]
 [183.28775]
 [197.8968 ]
 [144.44019]
 [103.71483]
 [144.60162]
 [102.28592]
 [173.02841]
 [156.40747]
 [141.78293]
 [140.05853]
 [191.28328]
 [161.58481]
 [145.39679]
 [187.87776]
 [156.71115]
 [172.07986]
 [182.26823]
 [162.42331]
 [170.68622]
 [173.49304]
 [163.02151]
 [159.27406]
 [194.37344]] 


 step:  540 
 Cost:  39.64726 
 Prediction:
 [[153.62283]
 [187.02094]
 [183.27951]
 [197.89943]
 [144.43091]
 [103.72696]
 [144.61827]
 [102.31853]
 [173.04227]
 [156.44676]
 [141.7898 ]
 [140.07378]
 [191.26302]
 [161.55199]
 [145.41617]
 [187.88533]
 [156.66866]
 [172.10504]
 [182.2457 ]
 [162.40424]
 [170.70294]
 [173.50133]
 [163.03336]
 [159.23694]
 [194.36385]] 


 step:  550 
 Cost:  39.414665 
 Prediction:
 [[153.61311]
 [187.01833]
 [183.27132]
 [197.90205]
 [144.42165]
 [103.73901]
 [144.63487]
 [102.35102]
 [173.05606]
 [156.48586]
 [141.79665]
 [140.08896]
 [191.24289]
 [161.5193 ]
 [145.43549]
 [187.8928

 step:  790 
 Cost:  34.321537 
 Prediction:
 [[153.39693 ]
 [186.95355 ]
 [183.0853  ]
 [197.96336 ]
 [144.20302 ]
 [104.007996]
 [145.01872 ]
 [103.10225 ]
 [173.36333 ]
 [157.37144 ]
 [141.95349 ]
 [140.43095 ]
 [190.78333 ]
 [160.77234 ]
 [145.87946 ]
 [188.06084 ]
 [155.65475 ]
 [172.71242 ]
 [181.7131  ]
 [161.95569 ]
 [171.10374 ]
 [173.69423 ]
 [163.31958 ]
 [158.36064 ]
 [194.13182 ]] 


 step:  800 
 Cost:  34.12834 
 Prediction:
 [[153.3886  ]
 [186.95078 ]
 [183.07799 ]
 [197.96585 ]
 [144.19406 ]
 [104.01841 ]
 [145.03413 ]
 [103.132385]
 [173.3752  ]
 [157.40623 ]
 [141.95973 ]
 [140.4443  ]
 [190.76515 ]
 [160.74272 ]
 [145.89717 ]
 [188.06734 ]
 [155.61606 ]
 [172.73584 ]
 [181.693   ]
 [161.93883 ]
 [171.11913 ]
 [173.7014  ]
 [163.33066 ]
 [158.32759 ]
 [194.12286 ]] 


 step:  810 
 Cost:  33.936646 
 Prediction:
 [[153.38033]
 [186.948  ]
 [183.0707 ]
 [197.96834]
 [144.18512]
 [104.02874]
 [145.04948]
 [103.16242]
 [173.387  ]
 [157.44086]
 [141.96597]
 [140.45761]

 Cost:  30.219353 
 Prediction:
 [[153.21805 ]
 [186.88834 ]
 [182.92493 ]
 [198.01929 ]
 [144.00026 ]
 [104.231995]
 [145.36168 ]
 [103.77297 ]
 [173.61897 ]
 [158.13153 ]
 [142.09167 ]
 [140.72176 ]
 [190.38364 ]
 [160.1198  ]
 [146.2719  ]
 [188.20079 ]
 [154.7995  ]
 [173.23505 ]
 [181.2723  ]
 [161.58699 ]
 [171.4453  ]
 [173.84883 ]
 [163.56674 ]
 [157.63661 ]
 [193.9318  ]] 


 step:  1030 
 Cost:  30.056234 
 Prediction:
 [[153.21086 ]
 [186.88545 ]
 [182.9183  ]
 [198.02167 ]
 [143.9916  ]
 [104.241035]
 [145.37607 ]
 [103.8011  ]
 [173.6293  ]
 [158.16272 ]
 [142.09743 ]
 [140.73364 ]
 [190.3671  ]
 [160.09274 ]
 [146.28827 ]
 [188.20645 ]
 [154.7639  ]
 [173.25702 ]
 [181.2541  ]
 [161.57184 ]
 [171.45958 ]
 [173.85509 ]
 [163.57713 ]
 [157.6068  ]
 [193.92336 ]] 


 step:  1040 
 Cost:  29.894264 
 Prediction:
 [[153.2037 ]
 [186.88257]
 [182.91174]
 [198.02403]
 [143.98294]
 [104.25003]
 [145.39041]
 [103.82913]
 [173.63956]
 [158.1938 ]
 [142.10315]
 [140.74548]
 [190.350

 step:  1250 
 Cost:  26.751764 
 Prediction:
 [[153.0637  ]
 [186.82089 ]
 [182.78032 ]
 [198.07256 ]
 [143.80426 ]
 [104.42662 ]
 [145.68204 ]
 [104.399055]
 [173.84093 ]
 [158.81364 ]
 [142.219   ]
 [140.98026 ]
 [190.02    ]
 [159.5235  ]
 [146.63469 ]
 [188.32248 ]
 [154.0121  ]
 [173.72537 ]
 [180.87392 ]
 [161.25609 ]
 [171.76286 ]
 [173.98395 ]
 [163.79936 ]
 [156.98343 ]
 [193.74377 ]] 


 step:  1260 
 Cost:  26.613708 
 Prediction:
 [[153.0575 ]
 [186.81792]
 [182.77435]
 [198.07481]
 [143.7959 ]
 [104.43447]
 [145.69547]
 [104.42532]
 [173.84985]
 [158.84166]
 [142.2243 ]
 [140.99081]
 [190.00497]
 [159.49876]
 [146.64983]
 [188.32738]
 [153.97931]
 [173.746  ]
 [180.85748]
 [161.24248]
 [171.77615]
 [173.98943]
 [163.80914]
 [156.95651]
 [193.73586]] 


 step:  1270 
 Cost:  26.47665 
 Prediction:
 [[153.05135]
 [186.81494]
 [182.76842]
 [198.07706]
 [143.78754]
 [104.44226]
 [145.70886]
 [104.45149]
 [173.85875]
 [158.86954]
 [142.22957]
 [141.00131]
 [189.98999]
 [159.47

 step:  1500 
 Cost:  23.581608 
 Prediction:
 [[152.92052]
 [186.7458 ]
 [182.6392 ]
 [198.12752]
 [143.59897]
 [104.60869]
 [146.00644]
 [105.03266]
 [174.0483 ]
 [159.47577]
 [142.3461 ]
 [141.22847]
 [189.66177]
 [158.93323]
 [146.99818]
 [188.43636]
 [153.22646]
 [174.22414]
 [180.48424]
 [160.93486]
 [172.0829 ]
 [174.11124]
 [164.03673]
 [156.3457 ]
 [193.55211]] 


 step:  1510 
 Cost:  23.466246 
 Prediction:
 [[152.91528 ]
 [186.74281 ]
 [182.6339  ]
 [198.12968 ]
 [143.59094 ]
 [104.615395]
 [146.01895 ]
 [105.057045]
 [174.05594 ]
 [159.50067 ]
 [142.35098 ]
 [141.23775 ]
 [189.64822 ]
 [158.91081 ]
 [147.01212 ]
 [188.44058 ]
 [153.19646 ]
 [174.2434  ]
 [180.46954 ]
 [160.92279 ]
 [172.09521 ]
 [174.11595 ]
 [164.04591 ]
 [156.32169 ]
 [193.54472 ]] 


 step:  1520 
 Cost:  23.351656 
 Prediction:
 [[152.91006 ]
 [186.73976 ]
 [182.62859 ]
 [198.1318  ]
 [143.58289 ]
 [104.62204 ]
 [146.03137 ]
 [105.081345]
 [174.06349 ]
 [159.52545 ]
 [142.3558  ]
 [141.24696 ]
 [189.63

 [193.37984]] 


 step:  1750 
 Cost:  20.92893 
 Prediction:
 [[152.79984]
 [186.6697 ]
 [182.51312]
 [198.17964]
 [143.40175]
 [104.7637 ]
 [146.3079 ]
 [105.62106]
 [174.22461]
 [160.06404]
 [142.46252]
 [141.44633]
 [189.33833]
 [158.39757]
 [147.33232]
 [188.53343]
 [152.50749]
 [174.68973]
 [180.13512]
 [160.64946]
 [172.37889]
 [174.2205 ]
 [164.25905]
 [155.77556]
 [193.3729 ]] 


 step:  1760 
 Cost:  20.832294 
 Prediction:
 [[152.79544]
 [186.66663]
 [182.50836]
 [198.18166]
 [143.39404]
 [104.76939]
 [146.31952]
 [105.64371]
 [174.23108]
 [160.08614]
 [142.46696]
 [141.45445]
 [189.32608]
 [158.37721]
 [147.34511]
 [188.53699]
 [152.48003]
 [174.7077 ]
 [180.12196]
 [160.63873]
 [172.39026]
 [174.22455]
 [164.26762]
 [155.75407]
 [193.36597]] 


 step:  1770 
 Cost:  20.736301 
 Prediction:
 [[152.79108 ]
 [186.66357 ]
 [182.50365 ]
 [198.18367 ]
 [143.38632 ]
 [104.77504 ]
 [146.3311  ]
 [105.666275]
 [174.23749 ]
 [160.10814 ]
 [142.4714  ]
 [141.46255 ]
 [189.31387 ]
 [1

### * another way to find out scores (almost the same results as above)

In [ ]:
# Lab 4 Multi-variable linear regression

tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['./INFLEARN_Deep_Learning_Zero_To_All/data-01-test-score.csv'],
    shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

## Default values, in case of empty columns. Also specifies the type of the decoded results
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

## Collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

## Placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

## Hypothesis
hypothesis = tf.matmul(X, W) + b

## Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

## Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

## Launch the graph in a session
config = tf.ConfigProto(
    device_count={'GPU': 0} # uncomment this line to force CPU
)
sess = tf.Session(config=config)

## Initailizes global variables in the graph
sess.run(tf.global_variables_initializer())

## Start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                    feed_dict={X:x_batch, Y:y_batch})
    if step % 10 == 0:
        print(' step: ', step, '\n',
              'Cost: ', cost_val,
              '\n Prediction:\n', hy_val, '\n\n')
        
coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

### ~ Section 4